# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-25 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201124_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='consult_courses',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Course', verbose_name='咨询课程'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='课程顾问'),
        ),
    ]
