# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-25 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20201125_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='consult_courses',
            field=models.ManyToManyField(to='app01.Course', verbose_name='咨询课程'),
        ),
    ]
