# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-25 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20201125_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'ordering': ['-id'], 'verbose_name_plural': '客户信息表'},
        ),
    ]
