# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-30 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_customerfollowup_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfollowup',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
