# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-30 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20201130_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'verbose_name_plural': '报名表'},
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='target',
            field=models.CharField(max_length=112, verbose_name='目标'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='why_us',
            field=models.CharField(max_length=112, verbose_name='为甚么加入'),
        ),
    ]
