# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20201130_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.CustomerInfo', verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_approved_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='合同审核时间'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_signed_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='合同签订日期'),
        ),
    ]
